version: '3'

services:
  db:
    image: postgres
    ports:
      - "8889:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
