# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'eventgroups',
            },
        ),
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=256)),
                ('repassword', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('group', models.ManyToManyField(blank=True, default=False, related_name='group_ids', to='event.EventGroups')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'eventusers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.EventUsers'),
        ),
    ]
