# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroupuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_group_user_id', to='event.EventGroups'),
        ),
        migrations.AlterField(
            model_name='eventgroupuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_group_user_id', to='event.EventUsers'),
        ),
        migrations.AlterModelTable(
            name='eventgroupuser',
            table='eventgroupuser',
        ),
    ]
