# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180205_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroupuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='eventgroupuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventgroups',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventGroupUser',
        ),
    ]
