# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180205_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='event.EventUsers')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-id'],
            },
        ),
    ]
